name: SP1 CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-prove:
    runs-on: ubuntu-latest

    steps:
      # 1. Установка Rust Toolchain
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: default
          override: true
          components: llvm-tools, rustc-dev

      # 2. Установка SP1 Toolchain
      - name: Install SP1 Toolchain
        run: |
          curl -L https://sp1up.succinct.xyz | bash
          ~/.sp1/bin/sp1up

      # 3. Клонирование кода
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 4. Компиляция программы SP1
      - name: Build SP1 Program
        run: |
          cd backend/program
          cargo prove build

      # 5. Генерация доказательств
      - name: Generate Proofs
        run: |
          cd backend/script
          RUST_LOG=info cargo run --release
